#!/usr/bin/env node

const { program } = require('commander');
program.version('0.0.1');
program.description('Compares two configuration files and shows a difference.');
program.option('-f, --format [type]', 'output format');
program.usage('[options] <filepath1> <filepath2>');
program.arguments('<filepath1>', '<filepath2>');
program.action((filepath1, filepath2) => {
  const file1 = filepath1;
  const file2 = filepath2;

  console.log('!111!', file1);
  console.log('!222!', file2);
});

console.log('');
program.parse(process.argv);

